disl: enter basic block ! index: 0 loopstart? false
disl: enter basic block ! index: 2 loopstart? true
disl: enter basic block ! index: 1 loopstart? false
app: 0
disl: enter basic block ! index: 2 loopstart? true
disl: enter basic block ! index: 1 loopstart? false
app: 1
disl: enter basic block ! index: 2 loopstart? true
disl: enter basic block ! index: 1 loopstart? false
app: 2
disl: enter basic block ! index: 2 loopstart? true
disl: enter basic block ! index: 1 loopstart? false
app: 3
disl: enter basic block ! index: 2 loopstart? true
disl: enter basic block ! index: 3 loopstart? false
