// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dislserver.proto

package ch.usi.dag.dislserver;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code InstrumentClassResult}
   */
  public enum InstrumentClassResult
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>CLASS_UNMODIFIED = 0;</code>
     */
    CLASS_UNMODIFIED(0),
    /**
     * <code>CLASS_MODIFIED = 1;</code>
     */
    CLASS_MODIFIED(1),
    /**
     * <code>ERROR = 3;</code>
     */
    ERROR(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CLASS_UNMODIFIED = 0;</code>
     */
    public static final int CLASS_UNMODIFIED_VALUE = 0;
    /**
     * <code>CLASS_MODIFIED = 1;</code>
     */
    public static final int CLASS_MODIFIED_VALUE = 1;
    /**
     * <code>ERROR = 3;</code>
     */
    public static final int ERROR_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static InstrumentClassResult valueOf(int value) {
      return forNumber(value);
    }

    public static InstrumentClassResult forNumber(int value) {
      switch (value) {
        case 0: return CLASS_UNMODIFIED;
        case 1: return CLASS_MODIFIED;
        case 3: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<InstrumentClassResult>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        InstrumentClassResult> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<InstrumentClassResult>() {
            public InstrumentClassResult findValueByNumber(int number) {
              return InstrumentClassResult.forNumber(number);
            }
          };

    private final int value;

    private InstrumentClassResult(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:InstrumentClassResult)
  }

  public interface InstrumentClassRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InstrumentClassRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 flags = 1;</code>
     */
    int getFlags();

    /**
     * <code>optional string className = 2;</code>
     */
    java.lang.String getClassName();
    /**
     * <code>optional string className = 2;</code>
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>optional bytes classBytes = 3;</code>
     */
    com.google.protobuf.ByteString getClassBytes();
  }
  /**
   * Protobuf type {@code InstrumentClassRequest}
   */
  public  static final class InstrumentClassRequest extends
      com.google.protobuf.GeneratedMessageLite<
          InstrumentClassRequest, InstrumentClassRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:InstrumentClassRequest)
      InstrumentClassRequestOrBuilder {
    private InstrumentClassRequest() {
      className_ = "";
      classBytes_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int FLAGS_FIELD_NUMBER = 1;
    private int flags_;
    /**
     * <code>optional int32 flags = 1;</code>
     */
    public int getFlags() {
      return flags_;
    }
    /**
     * <code>optional int32 flags = 1;</code>
     */
    private void setFlags(int value) {
      
      flags_ = value;
    }
    /**
     * <code>optional int32 flags = 1;</code>
     */
    private void clearFlags() {
      
      flags_ = 0;
    }

    public static final int CLASSNAME_FIELD_NUMBER = 2;
    private java.lang.String className_;
    /**
     * <code>optional string className = 2;</code>
     */
    public java.lang.String getClassName() {
      return className_;
    }
    /**
     * <code>optional string className = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(className_);
    }
    /**
     * <code>optional string className = 2;</code>
     */
    private void setClassName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      className_ = value;
    }
    /**
     * <code>optional string className = 2;</code>
     */
    private void clearClassName() {
      
      className_ = getDefaultInstance().getClassName();
    }
    /**
     * <code>optional string className = 2;</code>
     */
    private void setClassNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      className_ = value.toStringUtf8();
    }

    public static final int CLASSBYTES_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString classBytes_;
    /**
     * <code>optional bytes classBytes = 3;</code>
     */
    public com.google.protobuf.ByteString getClassBytes() {
      return classBytes_;
    }
    /**
     * <code>optional bytes classBytes = 3;</code>
     */
    private void setClassBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      classBytes_ = value;
    }
    /**
     * <code>optional bytes classBytes = 3;</code>
     */
    private void clearClassBytes() {
      
      classBytes_ = getDefaultInstance().getClassBytes();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (flags_ != 0) {
        output.writeInt32(1, flags_);
      }
      if (!className_.isEmpty()) {
        output.writeString(2, getClassName());
      }
      if (!classBytes_.isEmpty()) {
        output.writeBytes(3, classBytes_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (flags_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, flags_);
      }
      if (!className_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getClassName());
      }
      if (!classBytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, classBytes_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.usi.dag.dislserver.Protocol.InstrumentClassRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code InstrumentClassRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ch.usi.dag.dislserver.Protocol.InstrumentClassRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:InstrumentClassRequest)
        ch.usi.dag.dislserver.Protocol.InstrumentClassRequestOrBuilder {
      // Construct using ch.usi.dag.dislserver.Protocol.InstrumentClassRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int32 flags = 1;</code>
       */
      public int getFlags() {
        return instance.getFlags();
      }
      /**
       * <code>optional int32 flags = 1;</code>
       */
      public Builder setFlags(int value) {
        copyOnWrite();
        instance.setFlags(value);
        return this;
      }
      /**
       * <code>optional int32 flags = 1;</code>
       */
      public Builder clearFlags() {
        copyOnWrite();
        instance.clearFlags();
        return this;
      }

      /**
       * <code>optional string className = 2;</code>
       */
      public java.lang.String getClassName() {
        return instance.getClassName();
      }
      /**
       * <code>optional string className = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        return instance.getClassNameBytes();
      }
      /**
       * <code>optional string className = 2;</code>
       */
      public Builder setClassName(
          java.lang.String value) {
        copyOnWrite();
        instance.setClassName(value);
        return this;
      }
      /**
       * <code>optional string className = 2;</code>
       */
      public Builder clearClassName() {
        copyOnWrite();
        instance.clearClassName();
        return this;
      }
      /**
       * <code>optional string className = 2;</code>
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClassNameBytes(value);
        return this;
      }

      /**
       * <code>optional bytes classBytes = 3;</code>
       */
      public com.google.protobuf.ByteString getClassBytes() {
        return instance.getClassBytes();
      }
      /**
       * <code>optional bytes classBytes = 3;</code>
       */
      public Builder setClassBytes(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClassBytes(value);
        return this;
      }
      /**
       * <code>optional bytes classBytes = 3;</code>
       */
      public Builder clearClassBytes() {
        copyOnWrite();
        instance.clearClassBytes();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InstrumentClassRequest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ch.usi.dag.dislserver.Protocol.InstrumentClassRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ch.usi.dag.dislserver.Protocol.InstrumentClassRequest other = (ch.usi.dag.dislserver.Protocol.InstrumentClassRequest) arg1;
          flags_ = visitor.visitInt(flags_ != 0, flags_,
              other.flags_ != 0, other.flags_);
          className_ = visitor.visitString(!className_.isEmpty(), className_,
              !other.className_.isEmpty(), other.className_);
          classBytes_ = visitor.visitByteString(classBytes_ != com.google.protobuf.ByteString.EMPTY, classBytes_,
              other.classBytes_ != com.google.protobuf.ByteString.EMPTY, other.classBytes_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  flags_ = input.readInt32();
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  className_ = s;
                  break;
                }
                case 26: {

                  classBytes_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ch.usi.dag.dislserver.Protocol.InstrumentClassRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:InstrumentClassRequest)
    private static final ch.usi.dag.dislserver.Protocol.InstrumentClassRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InstrumentClassRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<InstrumentClassRequest> PARSER;

    public static com.google.protobuf.Parser<InstrumentClassRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface InstrumentClassResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InstrumentClassResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .InstrumentClassResult result = 1;</code>
     */
    int getResultValue();
    /**
     * <code>optional .InstrumentClassResult result = 1;</code>
     */
    ch.usi.dag.dislserver.Protocol.InstrumentClassResult getResult();

    /**
     * <code>optional string errorMessage = 2;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>optional string errorMessage = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();

    /**
     * <code>optional bytes classBytes = 3;</code>
     */
    com.google.protobuf.ByteString getClassBytes();
  }
  /**
   * Protobuf type {@code InstrumentClassResponse}
   */
  public  static final class InstrumentClassResponse extends
      com.google.protobuf.GeneratedMessageLite<
          InstrumentClassResponse, InstrumentClassResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:InstrumentClassResponse)
      InstrumentClassResponseOrBuilder {
    private InstrumentClassResponse() {
      errorMessage_ = "";
      classBytes_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>optional .InstrumentClassResult result = 1;</code>
     */
    public int getResultValue() {
      return result_;
    }
    /**
     * <code>optional .InstrumentClassResult result = 1;</code>
     */
    public ch.usi.dag.dislserver.Protocol.InstrumentClassResult getResult() {
      ch.usi.dag.dislserver.Protocol.InstrumentClassResult result = ch.usi.dag.dislserver.Protocol.InstrumentClassResult.forNumber(result_);
      return result == null ? ch.usi.dag.dislserver.Protocol.InstrumentClassResult.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .InstrumentClassResult result = 1;</code>
     */
    private void setResultValue(int value) {
        result_ = value;
    }
    /**
     * <code>optional .InstrumentClassResult result = 1;</code>
     */
    private void setResult(ch.usi.dag.dislserver.Protocol.InstrumentClassResult value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      result_ = value.getNumber();
    }
    /**
     * <code>optional .InstrumentClassResult result = 1;</code>
     */
    private void clearResult() {
      
      result_ = 0;
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 2;
    private java.lang.String errorMessage_;
    /**
     * <code>optional string errorMessage = 2;</code>
     */
    public java.lang.String getErrorMessage() {
      return errorMessage_;
    }
    /**
     * <code>optional string errorMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(errorMessage_);
    }
    /**
     * <code>optional string errorMessage = 2;</code>
     */
    private void setErrorMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorMessage_ = value;
    }
    /**
     * <code>optional string errorMessage = 2;</code>
     */
    private void clearErrorMessage() {
      
      errorMessage_ = getDefaultInstance().getErrorMessage();
    }
    /**
     * <code>optional string errorMessage = 2;</code>
     */
    private void setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorMessage_ = value.toStringUtf8();
    }

    public static final int CLASSBYTES_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString classBytes_;
    /**
     * <code>optional bytes classBytes = 3;</code>
     */
    public com.google.protobuf.ByteString getClassBytes() {
      return classBytes_;
    }
    /**
     * <code>optional bytes classBytes = 3;</code>
     */
    private void setClassBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      classBytes_ = value;
    }
    /**
     * <code>optional bytes classBytes = 3;</code>
     */
    private void clearClassBytes() {
      
      classBytes_ = getDefaultInstance().getClassBytes();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != ch.usi.dag.dislserver.Protocol.InstrumentClassResult.CLASS_UNMODIFIED.getNumber()) {
        output.writeEnum(1, result_);
      }
      if (!errorMessage_.isEmpty()) {
        output.writeString(2, getErrorMessage());
      }
      if (!classBytes_.isEmpty()) {
        output.writeBytes(3, classBytes_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != ch.usi.dag.dislserver.Protocol.InstrumentClassResult.CLASS_UNMODIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_);
      }
      if (!errorMessage_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getErrorMessage());
      }
      if (!classBytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, classBytes_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.usi.dag.dislserver.Protocol.InstrumentClassResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code InstrumentClassResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ch.usi.dag.dislserver.Protocol.InstrumentClassResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:InstrumentClassResponse)
        ch.usi.dag.dislserver.Protocol.InstrumentClassResponseOrBuilder {
      // Construct using ch.usi.dag.dislserver.Protocol.InstrumentClassResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .InstrumentClassResult result = 1;</code>
       */
      public int getResultValue() {
        return instance.getResultValue();
      }
      /**
       * <code>optional .InstrumentClassResult result = 1;</code>
       */
      public Builder setResultValue(int value) {
        copyOnWrite();
        instance.setResultValue(value);
        return this;
      }
      /**
       * <code>optional .InstrumentClassResult result = 1;</code>
       */
      public ch.usi.dag.dislserver.Protocol.InstrumentClassResult getResult() {
        return instance.getResult();
      }
      /**
       * <code>optional .InstrumentClassResult result = 1;</code>
       */
      public Builder setResult(ch.usi.dag.dislserver.Protocol.InstrumentClassResult value) {
        copyOnWrite();
        instance.setResult(value);
        return this;
      }
      /**
       * <code>optional .InstrumentClassResult result = 1;</code>
       */
      public Builder clearResult() {
        copyOnWrite();
        instance.clearResult();
        return this;
      }

      /**
       * <code>optional string errorMessage = 2;</code>
       */
      public java.lang.String getErrorMessage() {
        return instance.getErrorMessage();
      }
      /**
       * <code>optional string errorMessage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        return instance.getErrorMessageBytes();
      }
      /**
       * <code>optional string errorMessage = 2;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setErrorMessage(value);
        return this;
      }
      /**
       * <code>optional string errorMessage = 2;</code>
       */
      public Builder clearErrorMessage() {
        copyOnWrite();
        instance.clearErrorMessage();
        return this;
      }
      /**
       * <code>optional string errorMessage = 2;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setErrorMessageBytes(value);
        return this;
      }

      /**
       * <code>optional bytes classBytes = 3;</code>
       */
      public com.google.protobuf.ByteString getClassBytes() {
        return instance.getClassBytes();
      }
      /**
       * <code>optional bytes classBytes = 3;</code>
       */
      public Builder setClassBytes(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClassBytes(value);
        return this;
      }
      /**
       * <code>optional bytes classBytes = 3;</code>
       */
      public Builder clearClassBytes() {
        copyOnWrite();
        instance.clearClassBytes();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InstrumentClassResponse)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ch.usi.dag.dislserver.Protocol.InstrumentClassResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ch.usi.dag.dislserver.Protocol.InstrumentClassResponse other = (ch.usi.dag.dislserver.Protocol.InstrumentClassResponse) arg1;
          result_ = visitor.visitInt(result_ != 0, result_,    other.result_ != 0, other.result_);
          errorMessage_ = visitor.visitString(!errorMessage_.isEmpty(), errorMessage_,
              !other.errorMessage_.isEmpty(), other.errorMessage_);
          classBytes_ = visitor.visitByteString(classBytes_ != com.google.protobuf.ByteString.EMPTY, classBytes_,
              other.classBytes_ != com.google.protobuf.ByteString.EMPTY, other.classBytes_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();

                  result_ = rawValue;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  errorMessage_ = s;
                  break;
                }
                case 26: {

                  classBytes_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ch.usi.dag.dislserver.Protocol.InstrumentClassResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:InstrumentClassResponse)
    private static final ch.usi.dag.dislserver.Protocol.InstrumentClassResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InstrumentClassResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<InstrumentClassResponse> PARSER;

    public static com.google.protobuf.Parser<InstrumentClassResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
