// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dislserver.proto

package ch.usi.dag.dislserver;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code InstrumentClassResult}
   */
  public enum InstrumentClassResult
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>CLASS_UNMODIFIED = 0;</code>
     */
    CLASS_UNMODIFIED(0),
    /**
     * <code>CLASS_MODIFIED = 1;</code>
     */
    CLASS_MODIFIED(1),
    /**
     * <code>ERROR = 3;</code>
     */
    ERROR(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CLASS_UNMODIFIED = 0;</code>
     */
    public static final int CLASS_UNMODIFIED_VALUE = 0;
    /**
     * <code>CLASS_MODIFIED = 1;</code>
     */
    public static final int CLASS_MODIFIED_VALUE = 1;
    /**
     * <code>ERROR = 3;</code>
     */
    public static final int ERROR_VALUE = 3;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static InstrumentClassResult valueOf(int value) {
      return forNumber(value);
    }

    public static InstrumentClassResult forNumber(int value) {
      switch (value) {
        case 0: return CLASS_UNMODIFIED;
        case 1: return CLASS_MODIFIED;
        case 3: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<InstrumentClassResult>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        InstrumentClassResult> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<InstrumentClassResult>() {
            @java.lang.Override
            public InstrumentClassResult findValueByNumber(int number) {
              return InstrumentClassResult.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return InstrumentClassResultVerifier.INSTANCE;
    }

    private static final class InstrumentClassResultVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new InstrumentClassResultVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return InstrumentClassResult.forNumber(number) != null;
            }
          };

    private final int value;

    private InstrumentClassResult(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:InstrumentClassResult)
  }

  public interface InstrumentClassRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InstrumentClassRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 flags = 1;</code>
     * @return The flags.
     */
    int getFlags();

    /**
     * <code>string className = 2;</code>
     * @return The className.
     */
    java.lang.String getClassName();
    /**
     * <code>string className = 2;</code>
     * @return The bytes for className.
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>bytes classBytes = 3;</code>
     * @return The classBytes.
     */
    com.google.protobuf.ByteString getClassBytes();
  }
  /**
   * Protobuf type {@code InstrumentClassRequest}
   */
  public  static final class InstrumentClassRequest extends
      com.google.protobuf.GeneratedMessageLite<
          InstrumentClassRequest, InstrumentClassRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:InstrumentClassRequest)
      InstrumentClassRequestOrBuilder {
    private InstrumentClassRequest() {
      className_ = "";
      classBytes_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int FLAGS_FIELD_NUMBER = 1;
    private int flags_;
    /**
     * <code>int32 flags = 1;</code>
     * @return The flags.
     */
    @java.lang.Override
    public int getFlags() {
      return flags_;
    }
    /**
     * <code>int32 flags = 1;</code>
     * @param value The flags to set.
     */
    private void setFlags(int value) {
      
      flags_ = value;
    }
    /**
     * <code>int32 flags = 1;</code>
     */
    private void clearFlags() {
      
      flags_ = 0;
    }

    public static final int CLASSNAME_FIELD_NUMBER = 2;
    private java.lang.String className_;
    /**
     * <code>string className = 2;</code>
     * @return The className.
     */
    @java.lang.Override
    public java.lang.String getClassName() {
      return className_;
    }
    /**
     * <code>string className = 2;</code>
     * @return The bytes for className.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(className_);
    }
    /**
     * <code>string className = 2;</code>
     * @param value The className to set.
     */
    private void setClassName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      className_ = value;
    }
    /**
     * <code>string className = 2;</code>
     */
    private void clearClassName() {
      
      className_ = getDefaultInstance().getClassName();
    }
    /**
     * <code>string className = 2;</code>
     * @param value The bytes for className to set.
     */
    private void setClassNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      className_ = value.toStringUtf8();
    }

    public static final int CLASSBYTES_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString classBytes_;
    /**
     * <code>bytes classBytes = 3;</code>
     * @return The classBytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getClassBytes() {
      return classBytes_;
    }
    /**
     * <code>bytes classBytes = 3;</code>
     * @param value The classBytes to set.
     */
    private void setClassBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      classBytes_ = value;
    }
    /**
     * <code>bytes classBytes = 3;</code>
     */
    private void clearClassBytes() {
      
      classBytes_ = getDefaultInstance().getClassBytes();
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ch.usi.dag.dislserver.Protocol.InstrumentClassRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code InstrumentClassRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ch.usi.dag.dislserver.Protocol.InstrumentClassRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:InstrumentClassRequest)
        ch.usi.dag.dislserver.Protocol.InstrumentClassRequestOrBuilder {
      // Construct using ch.usi.dag.dislserver.Protocol.InstrumentClassRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 flags = 1;</code>
       * @return The flags.
       */
      @java.lang.Override
      public int getFlags() {
        return instance.getFlags();
      }
      /**
       * <code>int32 flags = 1;</code>
       * @param value The flags to set.
       * @return This builder for chaining.
       */
      public Builder setFlags(int value) {
        copyOnWrite();
        instance.setFlags(value);
        return this;
      }
      /**
       * <code>int32 flags = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlags() {
        copyOnWrite();
        instance.clearFlags();
        return this;
      }

      /**
       * <code>string className = 2;</code>
       * @return The className.
       */
      @java.lang.Override
      public java.lang.String getClassName() {
        return instance.getClassName();
      }
      /**
       * <code>string className = 2;</code>
       * @return The bytes for className.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        return instance.getClassNameBytes();
      }
      /**
       * <code>string className = 2;</code>
       * @param value The className to set.
       * @return This builder for chaining.
       */
      public Builder setClassName(
          java.lang.String value) {
        copyOnWrite();
        instance.setClassName(value);
        return this;
      }
      /**
       * <code>string className = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassName() {
        copyOnWrite();
        instance.clearClassName();
        return this;
      }
      /**
       * <code>string className = 2;</code>
       * @param value The bytes for className to set.
       * @return This builder for chaining.
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClassNameBytes(value);
        return this;
      }

      /**
       * <code>bytes classBytes = 3;</code>
       * @return The classBytes.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getClassBytes() {
        return instance.getClassBytes();
      }
      /**
       * <code>bytes classBytes = 3;</code>
       * @param value The classBytes to set.
       * @return This builder for chaining.
       */
      public Builder setClassBytes(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClassBytes(value);
        return this;
      }
      /**
       * <code>bytes classBytes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassBytes() {
        copyOnWrite();
        instance.clearClassBytes();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InstrumentClassRequest)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ch.usi.dag.dislserver.Protocol.InstrumentClassRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "flags_",
              "className_",
              "classBytes_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ch.usi.dag.dislserver.Protocol.InstrumentClassRequest> parser = PARSER;
          if (parser == null) {
            synchronized (ch.usi.dag.dislserver.Protocol.InstrumentClassRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ch.usi.dag.dislserver.Protocol.InstrumentClassRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:InstrumentClassRequest)
    private static final ch.usi.dag.dislserver.Protocol.InstrumentClassRequest DEFAULT_INSTANCE;
    static {
      InstrumentClassRequest defaultInstance = new InstrumentClassRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        InstrumentClassRequest.class, defaultInstance);
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<InstrumentClassRequest> PARSER;

    public static com.google.protobuf.Parser<InstrumentClassRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface InstrumentClassResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InstrumentClassResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    int getResultValue();
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @return The result.
     */
    ch.usi.dag.dislserver.Protocol.InstrumentClassResult getResult();

    /**
     * <code>string errorMessage = 2;</code>
     * @return The errorMessage.
     */
    java.lang.String getErrorMessage();
    /**
     * <code>string errorMessage = 2;</code>
     * @return The bytes for errorMessage.
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();

    /**
     * <code>bytes classBytes = 3;</code>
     * @return The classBytes.
     */
    com.google.protobuf.ByteString getClassBytes();
  }
  /**
   * Protobuf type {@code InstrumentClassResponse}
   */
  public  static final class InstrumentClassResponse extends
      com.google.protobuf.GeneratedMessageLite<
          InstrumentClassResponse, InstrumentClassResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:InstrumentClassResponse)
      InstrumentClassResponseOrBuilder {
    private InstrumentClassResponse() {
      errorMessage_ = "";
      classBytes_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    @java.lang.Override
    public int getResultValue() {
      return result_;
    }
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public ch.usi.dag.dislserver.Protocol.InstrumentClassResult getResult() {
      ch.usi.dag.dislserver.Protocol.InstrumentClassResult result = ch.usi.dag.dislserver.Protocol.InstrumentClassResult.forNumber(result_);
      return result == null ? ch.usi.dag.dislserver.Protocol.InstrumentClassResult.UNRECOGNIZED : result;
    }
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @param value The enum numeric value on the wire for result to set.
     */
    private void setResultValue(int value) {
        result_ = value;
    }
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     * @param value The result to set.
     */
    private void setResult(ch.usi.dag.dislserver.Protocol.InstrumentClassResult value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      result_ = value.getNumber();
    }
    /**
     * <code>.InstrumentClassResult result = 1;</code>
     */
    private void clearResult() {
      
      result_ = 0;
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 2;
    private java.lang.String errorMessage_;
    /**
     * <code>string errorMessage = 2;</code>
     * @return The errorMessage.
     */
    @java.lang.Override
    public java.lang.String getErrorMessage() {
      return errorMessage_;
    }
    /**
     * <code>string errorMessage = 2;</code>
     * @return The bytes for errorMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(errorMessage_);
    }
    /**
     * <code>string errorMessage = 2;</code>
     * @param value The errorMessage to set.
     */
    private void setErrorMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorMessage_ = value;
    }
    /**
     * <code>string errorMessage = 2;</code>
     */
    private void clearErrorMessage() {
      
      errorMessage_ = getDefaultInstance().getErrorMessage();
    }
    /**
     * <code>string errorMessage = 2;</code>
     * @param value The bytes for errorMessage to set.
     */
    private void setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorMessage_ = value.toStringUtf8();
    }

    public static final int CLASSBYTES_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString classBytes_;
    /**
     * <code>bytes classBytes = 3;</code>
     * @return The classBytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getClassBytes() {
      return classBytes_;
    }
    /**
     * <code>bytes classBytes = 3;</code>
     * @param value The classBytes to set.
     */
    private void setClassBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      classBytes_ = value;
    }
    /**
     * <code>bytes classBytes = 3;</code>
     */
    private void clearClassBytes() {
      
      classBytes_ = getDefaultInstance().getClassBytes();
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ch.usi.dag.dislserver.Protocol.InstrumentClassResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code InstrumentClassResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ch.usi.dag.dislserver.Protocol.InstrumentClassResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:InstrumentClassResponse)
        ch.usi.dag.dislserver.Protocol.InstrumentClassResponseOrBuilder {
      // Construct using ch.usi.dag.dislserver.Protocol.InstrumentClassResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @return The enum numeric value on the wire for result.
       */
      @java.lang.Override
      public int getResultValue() {
        return instance.getResultValue();
      }
      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResultValue(int value) {
        copyOnWrite();
        instance.setResultValue(value);
        return this;
      }
      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public ch.usi.dag.dislserver.Protocol.InstrumentClassResult getResult() {
        return instance.getResult();
      }
      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @param value The enum numeric value on the wire for result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(ch.usi.dag.dislserver.Protocol.InstrumentClassResult value) {
        copyOnWrite();
        instance.setResult(value);
        return this;
      }
      /**
       * <code>.InstrumentClassResult result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        copyOnWrite();
        instance.clearResult();
        return this;
      }

      /**
       * <code>string errorMessage = 2;</code>
       * @return The errorMessage.
       */
      @java.lang.Override
      public java.lang.String getErrorMessage() {
        return instance.getErrorMessage();
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @return The bytes for errorMessage.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        return instance.getErrorMessageBytes();
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @param value The errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setErrorMessage(value);
        return this;
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMessage() {
        copyOnWrite();
        instance.clearErrorMessage();
        return this;
      }
      /**
       * <code>string errorMessage = 2;</code>
       * @param value The bytes for errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setErrorMessageBytes(value);
        return this;
      }

      /**
       * <code>bytes classBytes = 3;</code>
       * @return The classBytes.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getClassBytes() {
        return instance.getClassBytes();
      }
      /**
       * <code>bytes classBytes = 3;</code>
       * @param value The classBytes to set.
       * @return This builder for chaining.
       */
      public Builder setClassBytes(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClassBytes(value);
        return this;
      }
      /**
       * <code>bytes classBytes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassBytes() {
        copyOnWrite();
        instance.clearClassBytes();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InstrumentClassResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ch.usi.dag.dislserver.Protocol.InstrumentClassResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "result_",
              "errorMessage_",
              "classBytes_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\f\u0002\u0208" +
                "\u0003\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ch.usi.dag.dislserver.Protocol.InstrumentClassResponse> parser = PARSER;
          if (parser == null) {
            synchronized (ch.usi.dag.dislserver.Protocol.InstrumentClassResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ch.usi.dag.dislserver.Protocol.InstrumentClassResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:InstrumentClassResponse)
    private static final ch.usi.dag.dislserver.Protocol.InstrumentClassResponse DEFAULT_INSTANCE;
    static {
      InstrumentClassResponse defaultInstance = new InstrumentClassResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        InstrumentClassResponse.class, defaultInstance);
    }

    public static ch.usi.dag.dislserver.Protocol.InstrumentClassResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<InstrumentClassResponse> PARSER;

    public static com.google.protobuf.Parser<InstrumentClassResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
